ACibler:
    type: entity
    table: has_targeted_taxa
    indexes:
        ce_cle_etrangere17:
            columns:
                - sampling_fk
        ce_cle_etrangere18:
            columns:
                - taxon_fk
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        collecteFk:
            targetEntity: Collecte
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sampling_fk:
                    referencedColumnName: id
            orphanRemoval: false
        referentielTaxonFk:
            targetEntity: ReferentielTaxon
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                taxon_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
