Adn:
    type: entity
    table: dna
    indexes:
        cle_etrangere:
            columns:
                - dna_extraction_method_voc_fk
        cle_etrangere1:
            columns:
                - date_precision_voc_fk
        adn_code_adn:
            columns:
                - dna_code
        cle_etrangere2:
            columns:
                - storage_box_fk
        cle_etrangere3:
            columns:
                - specimen_fk
        IDX_1DCF9AF9C53B46B:
            columns:
                - dna_quality_voc_fk
    uniqueConstraints:
        cu_adn_cle_primaire:
            columns:
                - dna_code
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codeAdn:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: dna_code
        dateAdn:
            type: date
            nullable: true
            column: dna_extraction_date
        concentrationNgMicrolitre:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: dna_concentration
        commentaireAdn:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: dna_comments
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        datePrecisionVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                date_precision_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        methodeExtractionAdnVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                dna_extraction_method_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        individuFk:
            targetEntity: Individu
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                specimen_fk:
                    referencedColumnName: id
            orphanRemoval: false
        qualiteAdnVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                dna_quality_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        boiteFk:
            targetEntity: Boite
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                storage_box_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
