Assigne:
    type: entity
    table: motu_number
    indexes:
        fk_12:
            columns:
                - delimitation_method_voc_fk
        fk_13:
            columns:
                - internal_sequence_fk
        fk_14:
            columns:
                - motu_fk
        fk_11:
            columns:
                - external_sequence_fk
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        numMotu:
            type: bigint
            nullable: false
            options:
                unsigned: false
            column: motu_number
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        sequenceAssembleeExtFk:
            targetEntity: SequenceAssembleeExt
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                external_sequence_fk:
                    referencedColumnName: id
            orphanRemoval: false
        methodeMotuVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                delimitation_method_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        sequenceAssembleeFk:
            targetEntity: SequenceAssemblee
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                internal_sequence_fk:
                    referencedColumnName: id
            orphanRemoval: false
        motuFk:
            targetEntity: Motu
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                motu_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
