Boite:
    type: entity
    table: storage_box
    indexes:
        fk_67:
            columns:
                - collection_code_voc_fk
        fk_68:
            columns:
                - box_type_voc_fk
        fk_66:
            columns:
                - collection_type_voc_fk
    uniqueConstraints:
        uk_storage_box__box_code:
            columns:
                - box_code
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codeBoite:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: box_code
        libelleBoite:
            type: string
            nullable: true
            length: 1024
            options:
                fixed: false
            column: box_title
        libelleCollection:
            type: string
            nullable: true
            length: 1024
            options:
                fixed: false
            column: libelle_collection
        commentaireBoite:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: box_comments
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        typeCollectionVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                collection_type_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        codeCollectionVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                collection_code_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        typeBoiteVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                box_type_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
