Chromatogramme:
    type: entity
    table: chromatogram
    indexes:
        fk_96:
            columns:
                - chromato_primer_voc_fk
        fk_98:
            columns:
                - institution_fk
        fk_99:
            columns:
                - pcr_fk
        fk_97:
            columns:
                - chromato_quality_voc_fk
    uniqueConstraints:
        uk_chromatogram__chromatogram_code:
            columns:
                - chromatogram_code
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codeChromato:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: chromatogram_code
        numYas:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: chromatogram_number
        commentaireChromato:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: chromatogram_comments
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        primerChromatoVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                chromato_primer_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        qualiteChromatoVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                chromato_quality_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        etablissementFk:
            targetEntity: Etablissement
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                institution_fk:
                    referencedColumnName: id
            orphanRemoval: false
        pcrFk:
            targetEntity: Pcr
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pcr_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
