Collecte:
    type: entity
    table: sampling
    indexes:
        ce_cle_etrangere60:
            columns:
                - date_precision_voc_fk
        ce_cle_etrangere61:
            columns:
                - donation_voc_fk
        ce_cle_etrangere62:
            columns:
                - site_fk
    uniqueConstraints:
        cu_collecte_cle_primaire:
            columns:
                - sample_code
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codeCollecte:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: sample_code
        dateCollecte:
            type: date
            nullable: true
            column: date_collecte
        dureeEchantillonnageMn:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: sampling_duration
        temperatureC:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: temperature
        conductiviteMicroSieCm:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: specific_conductance
        aFaire:
            type: smallint
            nullable: true
            options:
                unsigned: false
            column: sample_status
        commentaireCollecte:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: sampling_comments
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        datePrecisionVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                date_precision_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        legVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                donation_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        stationFk:
            targetEntity: Station
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                site_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
