Commune:
    type: entity
    table: municipality
    indexes:
        fk_39:
            columns:
                - country_fk
    uniqueConstraints:
        uk_municipality__municipality_code:
            columns:
                - municipality_code
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codeCommune:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: municipality_code
        nomCommune:
            type: string
            nullable: false
            length: 1024
            options:
                fixed: false
            column: municipality_name
        nomRegion:
            type: string
            nullable: false
            length: 1024
            options:
                fixed: false
            column: region_name
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        paysFk:
            targetEntity: Pays
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                country_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
