CompositionLotMateriel:
    type: entity
    table: composition_of_internal_biological_material
    indexes:
        fk_15:
            columns:
                - specimen_type_voc_fk
        fk_16:
            columns:
                - internal_biological_material_fk
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nbIndividus:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: number_of_specimens
        commentaireCompoLotMateriel:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: internal_biological_material_composition_comments
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        typeIndividuVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                specimen_type_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        lotMaterielFk:
            targetEntity: LotMateriel
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                internal_biological_material_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
