EstAligneEtTraite:
    type: entity
    table: chromatogram_is_processed_to
    indexes:
        ce_cle_etrangere37:
            columns:
                - chromatogram_fk
        ce_cle_etrangere38:
            columns:
                - internal_sequence_fk
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        chromatogrammeFk:
            targetEntity: Chromatogramme
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                chromatogram_fk:
                    referencedColumnName: id
            orphanRemoval: false
        sequenceAssembleeFk:
            targetEntity: SequenceAssemblee
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                internal_sequence_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
