EstIdentifiePar:
    type: entity
    table: species_is_identified_by
    indexes:
        ce_cle_etrangere10:
            columns:
                - person_fk
        ce_cle_etrangere9:
            columns:
                - identified_species_fk
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        personneFk:
            targetEntity: Personne
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                person_fk:
                    referencedColumnName: id
            orphanRemoval: false
        especeentifieeFk:
            targetEntity: EspeceIdentifiee
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                identified_species_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
