EstIdentifiePar:
    type: entity
    table: est_identifie_par
    indexes:
        ce_cle_etrangere10:
            columns:
                - personne_fk
        ce_cle_etrangere9:
            columns:
                - espece_identifiee_fk
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        dateCre:
            type: datetime
            nullable: true
            column: date_cre
        dateMaj:
            type: datetime
            nullable: true
            column: date_maj
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: user_cre
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: user_maj
    manyToOne:
        personneFk:
            targetEntity: Personne
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                personne_fk:
                    referencedColumnName: id
            orphanRemoval: false
        especeentifieeFk:
            targetEntity: EspeceIdentifiee
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                espece_identifiee_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
