Etablissement:
    type: entity
    table: institution
    uniqueConstraints:
        cu_etablissement_cle_primaire:
            columns:
                - institution_name
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nomEtablissement:
            type: string
            nullable: false
            length: 1024
            options:
                fixed: false
            column: institution_name
        commentaireEtablissement:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: institution_comments
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    lifecycleCallbacks: {  }
