Individu:
    type: entity
    table: specimen
    indexes:
        ce_cle_etrangere83:
            columns:
                - internal_biological_material_fk
        ce_cle_etrangere82:
            columns:
                - specimen_type_voc_fk
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codeIndBiomol:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: specimen_molecular_code
        codeIndTriMorpho:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: specimen_morphological_code
        codeTube:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: tube_code
        numIndBiomol:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: specimen_molecular_number
        commentaireInd:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: specimen_comments
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        typeIndividuVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                specimen_type_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        lotMaterielFk:
            targetEntity: LotMateriel
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                internal_biological_material_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
