IndividuLameEstRealisePar:
    type: entity
    table: individu_lame_est_realise_par
    indexes:
        ce_cle_etrangere26:
            columns:
                - personne_fk
        ce_cle_etrangere25:
            columns:
                - individu_lame_fk
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        individuLameFk:
            targetEntity: IndividuLame
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                individu_lame_fk:
                    referencedColumnName: id
            orphanRemoval: false
        personneFk:
            targetEntity: Personne
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                personne_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
