LotMaterielExtEstReferenceDans:
    type: entity
    table: external_biological_material_is_published_in
    indexes:
        fk_53:
            columns:
                - external_biological_material_fk
        fk_54:
            columns:
                - source_fk
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        sourceFk:
            targetEntity: Source
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                source_fk:
                    referencedColumnName: id
            orphanRemoval: false
        lotMaterielExtFk:
            targetEntity: LotMaterielExt
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                external_biological_material_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
