LotMaterielExt:
    type: entity
    table: external_biological_material
    indexes:
        ce_cle_etrangere46:
            columns:
                - sampling_fk
        ce_cle_etrangere49:
            columns:
                - pigmentation_voc_fk
        ce_cle_etrangere50:
            columns:
                - eyes_voc_fk
        ce_cle_etrangere47:
            columns:
                - date_precision_voc_fk
        ce_cle_etrangere48:
            columns:
                - number_of_specimens_voc_fk
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codeLotMaterielExt:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: external_biological_material_code
        dateCreationLotMaterielExt:
            type: date
            nullable: true
            column: external_biological_material_creation_date
        commentaireLotMaterielExt:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: external_biological_material_comments
        commentaireNbIndividus:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: number_of_specimens_comments
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        collecteFk:
            targetEntity: Collecte
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sampling_fk:
                    referencedColumnName: id
            orphanRemoval: false
        datePrecisionVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                date_precision_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        nbIndividusVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                number_of_specimens_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        pigmentationVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pigmentation_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        yeuxVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                eyes_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
