LotMaterielEstRealisePar:
    type: entity
    table: lot_materiel_est_realise_par
    indexes:
        ce_cle_etrangere27:
            columns:
                - lot_materiel_fk
        ce_cle_etrangere28:
            columns:
                - personne_fk
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        dateCre:
            type: datetime
            nullable: true
            column: date_cre
        dateMaj:
            type: datetime
            nullable: true
            column: date_maj
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: user_cre
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: user_maj
    manyToOne:
        personneFk:
            targetEntity: Personne
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                personne_fk:
                    referencedColumnName: id
            orphanRemoval: false
        lotMaterielFk:
            targetEntity: LotMateriel
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                lot_materiel_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
