LotMateriel:
    type: entity
    table: internal_biological_material
    indexes:
        ce_cle_etrangere69:
            columns:
                - date_precision_voc_fk
        ce_cle_etrangere71:
            columns:
                - eyes_voc_fk
        ce_cle_etrangere72:
            columns:
                - sampling_fk
        ce_cle_etrangere73:
            columns:
                - storage_box_fk
        ce_cle_etrangere70:
            columns:
                - pigmentation_voc_fk
    uniqueConstraints:
        cu_lot_materiel_cle_primaire:
            columns:
                - internal_biological_material_code
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codeLotMateriel:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: internal_biological_material_code
        dateLotMateriel:
            type: date
            nullable: true
            column: internal_biological_material_date
        commentaireConseilSqc:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: sequencing_advice
        commentaireLotMateriel:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: internal_biological_material_comments
        aFaire:
            type: smallint
            nullable: true
            options:
                unsigned: false
            column: internal_biological_material_status
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        datePrecisionVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                date_precision_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        pigmentationVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pigmentation_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        yeuxVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                eyes_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        collecteFk:
            targetEntity: Collecte
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sampling_fk:
                    referencedColumnName: id
            orphanRemoval: false
        boiteFk:
            targetEntity: Boite
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                storage_box_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
