Motu:
    type: entity
    table: motu
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nomFichierCsv:
            type: string
            nullable: false
            length: 1024
            options:
                fixed: false
            column: csv_file_name
        dateMotu:
            type: date
            nullable: false
            column: motu_date
        commentaireMotu:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: motu_comments
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
        libelleMotu:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: motu_title
    lifecycleCallbacks: {  }
