Pcr:
    type: entity
    table: pcr
    indexes:
        fk_95:
            columns:
                - dna_fk
        fk_94:
            columns:
                - date_precision_voc_fk
        fk_89:
            columns:
                - gene_voc_fk
        fk_92:
            columns:
                - forward_primer_voc_fk
        fk_93:
            columns:
                - reverse_primer_voc_fk
        fk_90:
            columns:
                - pcr_quality_voc_fk
        fk_91:
            columns:
                - pcr_specificity_voc_fk
    uniqueConstraints:
        uk_pcr__pcr_code:
            columns:
                - pcr_code
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codePcr:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: pcr_code
        numPcr:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: pcr_number
        datePcr:
            type: date
            nullable: true
            column: pcr_date
        detailPcr:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: pcr_details
        remarquePcr:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: pcr_comments
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        geneVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                gene_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        qualitePcrVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pcr_quality_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        specificiteVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pcr_specificity_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        primerPcrStartVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                forward_primer_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        primerPcrEndVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                reverse_primer_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        datePrecisionVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                date_precision_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        adnFk:
            targetEntity: Adn
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                dna_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
