Programme:
    type: entity
    table: program
    uniqueConstraints:
        cu_programme_cle_primaire:
            columns:
                - program_code
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codeProgramme:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: program_code
        nomProgramme:
            type: string
            nullable: false
            length: 1024
            options:
                fixed: false
            column: program_name
        nomsResponsables:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
            column: coordinator_names
        typeFinanceur:
            type: string
            nullable: true
            length: 1024
            options:
                fixed: false
            column: funding_agency
        anneeDebut:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: starting_year
        anneeFin:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: ending_year
        commentaireProgramme:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: program_comments
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    lifecycleCallbacks: {  }
