ReferentielTaxon:
    type: entity
    table: taxon
    uniqueConstraints:
        uk_taxon__taxon_name:
            columns:
                - taxon_name
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        taxon_name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        taxon_rank:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        subclass:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        taxon_order:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        family:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        genus:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        species:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        subspecies:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        taxon_validity:
            type: smallint
            nullable: false
            options:
                unsigned: false
        codeTaxon:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: taxon_code
        commentaireRef:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: taxon_comments
        objectif:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        clade:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        taxnameRef:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: taxon_synonym
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    lifecycleCallbacks: {  }
