SequenceAssemblee:
    type: entity
    table: sequence_assemblee
    indexes:
        ce_cle_etrangere35:
            columns:
                - date_precision_voc_fk
        ce_cle_etrangere36:
            columns:
                - statut_sqc_ass_voc_fk
    uniqueConstraints:
        cu_sequence_assemblee_cle_primaire:
            columns:
                - code_sqc_ass
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codeSqcAss:
            type: string
            nullable: false
            length: 1024
            options:
                fixed: false
            column: code_sqc_ass
        dateCreationSqcAss:
            type: date
            nullable: true
            column: date_creation_sqc_ass
        accessionNumber:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: accession_number
        codeSqcAlignement:
            type: string
            nullable: true
            length: 1024
            options:
                fixed: false
            column: code_sqc_alignement
        commentaireSqcAss:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: commentaire_sqc_ass
        dateCre:
            type: datetime
            nullable: true
            column: date_cre
        dateMaj:
            type: datetime
            nullable: true
            column: date_maj
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: user_cre
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: user_maj
    manyToOne:
        datePrecisionVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                date_precision_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        statutSqcAssVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                statut_sqc_ass_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
