SequenceAssembleeExt:
    type: entity
    table: external_sequence
    indexes:
        ce_cle_etrangere4:
            columns:
                - external_sequence_origin_voc_fk
        ce_cle_etrangere6:
            columns:
                - external_sequence_status_voc_fk
        ce_cle_etrangere2:
            columns:
                - gene_voc_fk
        ce_cle_etrangere3:
            columns:
                - date_precision_voc_fk
        ce_cle_etrangere5:
            columns:
                - sampling_fk
    uniqueConstraints:
        cu_sequence_assemblee_ext_cle_primaire:
            columns:
                - external_sequence_code
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codeSqcAssExt:
            type: string
            nullable: false
            length: 1024
            options:
                fixed: false
            column: external_sequence_code
        dateCreationSqcAssExt:
            type: date
            nullable: true
            column: external_sequence_creation_date
        accessionNumberSqcAssExt:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
            column: external_sequence_accession_number
        codeSqcAssExtAlignement:
            type: string
            nullable: true
            length: 1024
            options:
                fixed: false
            column: external_sequence_alignment_code
        numIndividuSqcAssExt:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: external_sequence_specimen_number
        taxonOrigineSqcAssExt:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: external_sequence_primary_taxon
        commentaireSqcAssExt:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: external_sequence_comments
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        geneVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                gene_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        datePrecisionVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                date_precision_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        origineSqcAssExtVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                external_sequence_origin_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        collecteFk:
            targetEntity: Collecte
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sampling_fk:
                    referencedColumnName: id
            orphanRemoval: false
        statutSqcAssVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                external_sequence_status_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
