SequenceAssemblee:
    type: entity
    table: internal_sequence
    indexes:
        ce_cle_etrangere35:
            columns:
                - date_precision_voc_fk
        ce_cle_etrangere36:
            columns:
                - internal_sequence_status_voc_fk
    uniqueConstraints:
        cu_sequence_assemblee_cle_primaire:
            columns:
                - internal_sequence_code
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codeSqcAss:
            type: string
            nullable: false
            length: 1024
            options:
                fixed: false
            column: internal_sequence_code
        dateCreationSqcAss:
            type: date
            nullable: true
            column: internal_sequence_creation_date
        accessionNumber:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: internal_sequence_accession_number
        codeSqcAlignement:
            type: string
            nullable: true
            length: 1024
            options:
                fixed: false
            column: internal_sequence_alignment_code
        commentaireSqcAss:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: internal_sequence_comments
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        datePrecisionVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                date_precision_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        statutSqcAssVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                internal_sequence_status_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
