Source:
    type: entity
    table: source
    uniqueConstraints:
        cu_source_cle_primaire:
            columns:
                - source_code
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codeSource:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: source_code
        anneeSource:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: source_year
        libelleSource:
            type: string
            nullable: false
            length: 2048
            options:
                fixed: false
            column: source_title
        commentaireSource:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: source_comments
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    lifecycleCallbacks: {  }
