SqcExtEstReferenceDans:
    type: entity
    table: sqc_ext_est_reference_dans
    indexes:
        ce_cle_etrangere7:
            columns:
                - source_fk
        ce_cle_etrangere8:
            columns:
                - sequence_assemblee_ext_fk
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        sourceFk:
            targetEntity: Source
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                source_fk:
                    referencedColumnName: id
            orphanRemoval: false
        sequenceAssembleeExtFk:
            targetEntity: SequenceAssembleeExt
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sequence_assemblee_ext_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
