SqcExtEstRealisePar:
    type: entity
    table: sqc_ext_est_realise_par
    indexes:
        ce_cle_etrangere32:
            columns:
                - personne_fk
        ce_cle_etrangere31:
            columns:
                - sequence_assemblee_ext_fk
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        dateCre:
            type: datetime
            nullable: true
            column: date_cre
        dateMaj:
            type: datetime
            nullable: true
            column: date_maj
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: user_cre
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: user_maj
    manyToOne:
        sequenceAssembleeExtFk:
            targetEntity: SequenceAssembleeExt
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sequence_assemblee_ext_fk:
                    referencedColumnName: id
            orphanRemoval: false
        personneFk:
            targetEntity: Personne
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                personne_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
