Station:
    type: entity
    table: site
    indexes:
        ce_cle_etrangere56:
            columns:
                - country_fk
        ce_cle_etrangere58:
            columns:
                - habitat_type_voc_fk
        ce_cle_etrangere59:
            columns:
                - coordinate_precision_voc_fk
        ce_cle_etrangere57:
            columns:
                - access_point_voc_fk
        ce_cle_etrangere55:
            columns:
                - municipality_fk
    uniqueConstraints:
        cu_station_cle_primaire:
            columns:
                - site_code
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codeStation:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: site_code
        nomStation:
            type: string
            nullable: false
            length: 1024
            options:
                fixed: false
            column: site_name
        latDegDec:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: latitude
        longDegDec:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: longitude
        altitudeM:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: elevation
        infoLocalisation:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: location_info
        infoDescription:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: site_description
        commentaireStation:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: site_comments
        dateCre:
            type: datetime
            nullable: true
            column: date_of_creation
        dateMaj:
            type: datetime
            nullable: true
            column: date_of_update
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: creation_user_name
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: update_user_name
    manyToOne:
        communeFk:
            targetEntity: Commune
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                municipality_fk:
                    referencedColumnName: id
            orphanRemoval: false
        paysFk:
            targetEntity: Pays
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                country_fk:
                    referencedColumnName: id
            orphanRemoval: false
        pointAccesVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                access_point_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        habitatTypeVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                habitat_type_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        precisionLatLongVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                coordinate_precision_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
